### ISSUE TITLE
Minecraft 12.2 Graphical glitches when using arrows

### ISSUE THREAD

**Issue by Garulf** [baguchan/HunterIllager#7]
Seeing strange floating and flickering entities whenever a Illager uses his bow. Also Optifine is logging a OpenGL Error: 1283 (Stackoverflow).

Modlist: [MC Eternal Modpack](https://www.curseforge.com/minecraft/modpacks/minecraft-eternal)
(Optifine added for shader support)

Entity idle state:
![2021-10-16_08 10 57](https://user-images.githubusercontent.com/535299/137586861-7c3ba150-ab73-4843-ba98-902e17e0b6fe.png)

Entity Attack state:
![2021-10-16_08 11 19](https://user-images.githubusercontent.com/535299/137586873-5b293696-c3b8-436b-bc82-f37a25298151.png)

Water visually disappears, random entities flicker and render upside-down. The visual bugs lessen when Illager is faced head on.

**Comment by Garulf** [comment]
```
[11:40:30] [Client thread/ERROR] [minecraft/RenderLivingBase]: Couldn't render entity
java.lang.ClassCastException: baguchan.hunterillager.client.model.ModelHunterIllager cannot be cast to net.minecraft.client.model.ModelBiped
	at com.vicmatskiv.weaponlib.compatibility.Interceptors.positionItemSide(Interceptors.java:249) ~[Interceptors.class:?]
	at net.minecraft.client.renderer.entity.layers.LayerHeldItem.func_188358_a(LayerHeldItem.java:58) ~[ccc.class:?]
	at net.minecraft.client.renderer.entity.layers.LayerHeldItem.func_177141_a(LayerHeldItem.java:41) ~[ccc.class:?]
	at baguchan.hunterillager.client.render.RenderHunterIllager$1.func_177141_a(RenderHunterIllager.java:31) ~[RenderHunterIllager$1.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_177093_a(RenderLivingBase.java:561) ~[caa.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:270) [caa.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(RenderLiving.java:50) [caf.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(RenderLiving.java:16) [caf.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:413) [bzf.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:393) [bzf.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:850) [buy.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1808) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1621) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1390) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

Only happens when the mod (vics-modern-warfare-mod)[https://www.curseforge.com/minecraft/mc-mods/vics-modern-warfare-mod] is loaded.

**Comment by Garulf** [comment]
Seems this is an issue on vics-modern-warfare-mod side as it happens with all illager entities.
